# Generated by Django

from django.db import migrations # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('recipecraft', '0005_remove_userprofile_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='following',
        ),
    ]
