# Generated by Django


from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('recipecraft', '0002_alter_rating_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
